kango.Browser=function(){this.superclass.apply(this,arguments);this._lastTabId=0;this._tabs={};safari.application.addEventListener("beforeNavigate",kango.lang.bind(this._onBeforeNavigate,this),!0);safari.application.addEventListener("navigate",kango.lang.bind(this._onNavigate,this),!0);safari.application.addEventListener("activate",kango.lang.bind(this._onActivate,this),!0);safari.application.addEventListener("open",kango.lang.bind(this._onOpen,this),!0);safari.application.addEventListener("close",
kango.lang.bind(this._onClose,this),!0)};
kango.Browser.prototype=kango.oop.extend(kango.BrowserBase,{_lastTabId:0,_tabs:null,_generateTabId:function(){return this._lastTabId++},_registerTab:function(a){var b=this._generateTabId();this._tabs[b]=a;return b},_unregisterTab:function(a){a=this._getTabId(a);return-1!=a?delete this._tabs[a]:!1},_getTabId:function(a){for(var b in this._tabs)if(this._tabs.hasOwnProperty(b)&&this._tabs[b]===a)return b;return-1},_onOpen:function(a){a.target instanceof SafariBrowserTab&&(a=this.getKangoTab(a.target),
kango.browser.fireEvent(this.event.TAB_CREATED,{target:a,tabId:a.getId()}))},_onClose:function(a){a.target instanceof SafariBrowserTab&&(a=a.target,this.fireEvent(this.event.TAB_REMOVED,{tabId:this._getTabId(a)}),this._unregisterTab(a))},_onActivate:function(a){a.target instanceof SafariBrowserTab&&(a=this.getKangoTab(a.target),kango.browser.fireEvent(this.event.TAB_CHANGED,{url:a.getUrl(),title:a.getTitle(),target:a,tabId:a.getId()}))},_onBeforeNavigate:function(a){var b=this.getKangoTab(a.target);
this.fireEvent(this.event.BEFORE_NAVIGATE,{url:a.url||"",target:b})},_onNavigate:function(a){a=this.getKangoTab(a.target);this.fireEvent(this.event.DOCUMENT_COMPLETE,{url:a.getUrl(),title:a.getTitle(),target:a})},getKangoTab:function(a){var b=this._getTabId(a);-1==b&&(b=this._registerTab(a));return new kango.BrowserTab(a,b)},getName:function(){return"safari"},windows:{getAll:function(a){a(kango.array.map(safari.application.browserWindows,function(a){return new kango.BrowserWindow(a)}))},getCurrent:function(a){a(new kango.BrowserWindow(safari.application.activeBrowserWindow))},
create:function(a){safari.application.openBrowserWindow().activeTab.url=a.url}},tabs:{getAll:function(a){for(var b=[],e=safari.application.browserWindows,c=0;c<e.length;c++)for(var f=e[c].tabs,d=0;d<f.length;d++)b.push(kango.browser.getKangoTab(f[d]));a(b)},getCurrent:function(a){a(kango.browser.getKangoTab(safari.application.activeBrowserWindow.activeTab))},create:function(a){safari.application.activeBrowserWindow.openTab(("undefined"!=typeof a.focused?a.focused:1)?"foreground":"background").url=
a.url}}});kango.BrowserWindow=function(a){this._window=a};kango.BrowserWindow.prototype=kango.oop.extend(kango.IBrowserWindow,{_window:null,getTabs:function(a){a(kango.array.map(this._window.tabs,function(a){return kango.browser.getKangoTab(a)}))},getCurrentTab:function(a){a(kango.browser.getKangoTab(this._window.activeTab))},isActive:function(){return safari.application.activeBrowserWindow==this._window}});kango.BrowserTab=function(a,b){this._tab=a;this._id=b};
kango.BrowserTab.prototype=kango.oop.extend(kango.IBrowserTab,{_id:null,_tab:null,getId:function(){return this._id},getUrl:function(){return this._tab.url||""},getTitle:function(){return this._tab.title||""},getDOMWindow:function(){return null},isActive:function(){return this._tab==this._tab.browserWindow.activeTab},navigate:function(a){this._tab.url=a},dispatchMessage:function(a,b){return"undefined"!=typeof this._tab.page?(this._tab.page.dispatchMessage(a,b),!0):!1},close:function(){this._tab.close()}});
kango.browser=new kango.Browser;
