var kango={oop:{extend:function(a,b){var c=function(){};c.prototype=a.prototype;c=new c;c.superclass=a;this.mixin(c,b);return c},mixin:function(a,b){for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c])},createProxy:function(a){var b=function(){};b.prototype=a;b=new b;b.baseObject=a;return b},decorate:function(a,b,c){var d=a[b];a[b]=function(){return c.call(this,d,arguments)}}},array:{map:function(a,b){for(var c=a.length,d=Array(c),e=0;e<c;e++)d[e]=b(a[e]);return d},forEach:function(a,b){for(var c=a.length,
d=0;d<c;d++)b(a[d])}},string:{format:function(a,b){for(var c=1;c<arguments.length;c++)a=a.replace(RegExp("\\{"+(c-1)+"}","g"),arguments[c].toString());return a},isAlpha:function(a){return"a"<=a&&"z">=a||"A"<=a&&"Z">=a},isDigit:function(a){return"0"<=a&&"9">=a}},object:{getKeys:function(a){var b=[],c;for(c in a)a.hasOwnProperty(c)&&b.push(c);return b}},date:{diff:function(a,b){return Math.ceil((a.getTime()-b.getTime())/1E3)}},ExtensionInfo:function(){this.homepage_url=this.creator=this.description=
this.version=this.name="";this.background_scripts=[];this.content_scripts=[];this.browser_button={};this.options_page=this.update_path_url=""},NotImplementedException:function(a){this.prototype=Error.prototype;this.name="KangoNotImplementedException";this.message="Method "+(a?a+" ":"")+"is not implemented";this.toString=function(){return this.name+": "+this.message}},event:{READY:"Ready",Ready:"Ready",MESSAGE:"message",Message:"message",UNINSTALL:"Uninstall"},Event:function(a,b,c){this.type=a;this.target=
c||null;"object"==typeof b&&kango.oop.mixin(this,b)},EventTarget:function(){this._eventListeners={}}};
kango.EventTarget.prototype={_eventListeners:{},dispatchEvent:function(a){var b=a.type.toLowerCase();if("undefined"!=typeof this._eventListeners[b]){for(var b=this._eventListeners[b],c=0;c<b.length;c++)b[c](a);return!0}return!1},fireEvent:function(a,b){return this.dispatchEvent(new kango.Event(a,b))},addEventListener:function(a,b){if("undefined"!=typeof b.call&&"undefined"!=typeof b.apply){for(var c=a.toLowerCase(),c=this._eventListeners[c]=this._eventListeners[c]||[],d=0;d<c.length;d++)if(c[d]==
b)return!1;c.push(b);return!0}return!1},removeEventListener:function(a,b){var c=a.toLowerCase();if("undefined"!=typeof this._eventListeners[c])for(var c=this._eventListeners[c],d=0;d<c.length;d++)if(c[d]==b)return c.splice(d,1),!0;return!1}};kango.IConsole=function(){};kango.IConsole.prototype={log:function(){throw new kango.NotImplementedException;}};kango.IStorage=function(){};
kango.IStorage.prototype={SYSTEM_STORAGE_PREFIX:"{772ED927-1623-4E2C-94CC-D5E488E34C5B}_KangoSystemStorage.",setItem:function(){throw new kango.NotImplementedException;},getItem:function(){throw new kango.NotImplementedException;},removeItem:function(){throw new kango.NotImplementedException;},getKeys:function(){throw new kango.NotImplementedException;},clear:function(){throw new kango.NotImplementedException;}};kango.IOBase=function(){};
kango.IOBase.prototype={getExtensionFileUrl:function(){throw new kango.NotImplementedException;},isLocalUrl:function(a){return-1==a.indexOf("http://")&&-1==a.indexOf("https://")},getFileUrl:function(a){this.isLocalUrl(a)&&(a=this.getExtensionFileUrl(a));return a},getExtensionFileContents:function(a){var b=new XMLHttpRequest;b.open("GET",this.getExtensionFileUrl(a),!1);"undefined"!=typeof b.overrideMimeType&&b.overrideMimeType("text/plain");try{return b.send(null),b.responseText}catch(c){return null}},
getResourceUrl:function(){throw new kango.NotImplementedException;}};kango.LangBase=function(){};
kango.LangBase.prototype={getGlobalContext:function(){return function(){return this}.call(null)},invoke:function(a,b,c){for(var b=b.split("."),d=b.pop(),e=0;e<b.length;e++)a=a[b[e]];return a[d].apply(a,c)},evalInSandbox:function(){throw new kango.NotImplementedException;},bind:function(a,b){return function(){a.apply(b,arguments)}},clone:function(a){return JSON.parse(JSON.stringify(a))},isString:function(a){return"string"==typeof a||a instanceof String},isObject:function(a){return"object"==typeof a||
"[object Object]"==Object.prototype.toString.call(a)},isArray:function(a){return a instanceof Array||"[object Array]"==Object.prototype.toString.call(a)},isFunction:function(a){return"function"==typeof a}};
(function(){kango.oop.mixin(kango,kango.EventTarget.prototype);kango.oop.mixin(kango,new kango.EventTarget);kango.oop.mixin(kango,{_configFileName:"extension_info.json",_extensionInfo:null,_messageRouter:null,_eventState:0,_modules:[],_loadExtensionInfo:function(){null==this._extensionInfo&&(this._extensionInfo=JSON.parse(kango.io.getExtensionFileContents(this._configFileName)))},_initMessaging:function(){var a=this;this._messageRouter=new kango.MessageRouter;this._messageRouter.onmessage=function(b){a.fireEvent(a.event.MESSAGE,
b)};this.dispatchMessage=function(a,c){this._messageRouter.dispatchMessage(a,c)}},_initModules:function(){for(var a=0;a<this._modules.length;a++)(new this._modules[a]).init(kango)},_init:function(){this._loadExtensionInfo();this._initMessaging();this._initModules();return this.fireEvent(this.event.READY)},registerModule:function(a){this._modules.push(a)},getExtensionInfo:function(){null==this._extensionInfo&&this._loadExtensionInfo();return kango.lang.clone(this._extensionInfo)},getContext:function(){var a=
kango.backgroundScript.getContext();return a?a:kango.lang.getGlobalContext()},isDebug:function(){var a=this.getExtensionInfo();return"undefined"!=typeof a.debug&&a.debug}})})();
